name: Elefantel
description: >
    Machine Learning projects typically in Python and Golang
about: >
    Software engineer with love for Fintech, Machine Learning and Startups

master_repo: false
url: "http://elefante.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           whitepaper
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "mpendulo@elefantel.com"
  # Social networking links used in footer. 
  twitter: mpexgem
  github: https://github.com/elefantel
  linkedin: https://www.linkedin.com/in/mpexgem/

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
