name: "ザリガニの揺れる川"
description: "ザリガニの揺れる川"
about: "ザリガニの揺れる川"

master_repo: false
url: "http://crayfish-ghost.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed', 'jekyll-sitemap']

paginate: 2

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Urabe Yodogawa. Powered by <a href="https://jekyllrb.com" rel="nofollow" target="_blank" rel="noopener">jekyll</a> & <a href="https://github.com/vinitkumar/white-paper" rel="nofollow" target="_blank" rel="noopener">white-paper</a>.
  avatar:         #"https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          #"vinit1414.08@bitmesra.ac.in"
  # Social networking links used in footer. Update and remove as you like.
  twitter: #vinitkme
  github: #https://github.com/vinitkumar
  stackexchange: #https://stackoverflow.com/users/859112/vinit-kumar?tab=profile
  linkedin: #https://www.linkedin.com/in/vinitatlinkedin
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
