name: Sayid.so
description: >
    Website Soomaliyeed, halkan waxaad kagala soconkartaa arima ku saabsan talo, waano, diini iyo danta umada afka Somaliga.
about: >
    Sayid.so coming soon

master_repo: false
url: "http://sayid.so/sayid.so"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist']

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           sayid.so
  avatar:         ""
  email:          ""
  # Social networking links used in footer. Update and remove as you like.
  twitter:@sayidcalawi
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
